### ISSUE TITLE
Invalid hook call

### ISSUE THREAD

**Issue by blackinitial** [bymattlee/bymattlee-sanity-starter-cms#12]
hello sir @bymattlee , im not familiar on react, i implementation your code on my project about youtubeEmbed.js but i got some error like this:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```
im try to debug but dont got where is that.
my code is same like your code, maybe you know about this
thanks

**Comment by bymattlee** [comment]
Hi,

I have not been able to replicate the issue. Can you try using Node 12.22.0?

I removed the node_modules directory and yarn.lock file and was able to reinstall with no issues.
